package fr.aquillet.kiwi.command;

public interface Commands {

	String HIDE_APPLICATION = "COMMAND_HIDE_APPLICATION";
	String SHOW_APPLICATION = "COMMAND_SHOW_APPLICATION";
	String OPEN_DIALOG_IN_PARENT = "COMMAND_OPEN_DIALOG_IN_PARENT";
	String CLOSE_DIALOG = "COMMAND_CLOSE_DIALOG";

	String APPLICATION = "COMMAND_APPLICATION";
	String LAUNCHER = "COMMAND_LAUNCHER";
	String LABEL = "COMMAND_LABEL";
	String SCENARIO = "COMMAND_SCENARIO";
	String CAMPAIGN = "COMMAND_CAMPAIGN";

}
